# Ruff (linter + import sorter)
line-length = 100
target-version = "py313"
src = ["src"]                 # treat code under src/ as first-party
extend-exclude = ["data", ".venv", "build", "dist"]

[lint]
# Rule sets: pycodestyle (E), pyflakes (F), isort (I), bugbear (B), pyupgrade (UP), pylint-like (PL)
select = ["E", "F", "I", "B", "UP", "PL"]
# Don't suggest datetime.UTC; we use timezone.utc for clarity.
ignore = ["UP017"]

[lint.per-file-ignores]
# Allow magic numbers in tests
"tests/*" = ["PLR2004"]

[lint.isort]
combine-as-imports = true
force-sort-within-sections = true

[format]
# Let Ruff’s formatter mirror Black’s defaults, with 100 col width
quote-style = "double"
indent-style = "space"
