name: CI
on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.12", "3.13"]
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
          cache: "pip"

      - name: Upgrade pip
        run: python -m pip install --upgrade pip

      - name: Install project (dev extras)
        run: pip install -e ".[dev]"

      - name: Lint (Ruff)
        run: ruff check src tests

      - name: Format check (Black)
        run: black --check .

      - name: Type-check (mypy)
        run: mypy -p learn

      - name: Smoke test (CLI entrypoint)
        run: learn --help

      - name: Test (pytest)
        run: pytest -q